version: '3'

services:
  marionette:
    image: dollarkiller/marionette_go:latest
    restart: always
    environment:
      LISTENADDR: "0.0.0.0:6063"

  nginx:
    image: nginx:1-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - marionette
    ports:
      - "6063:6063"

# docker-compose scale marionette=10